-- AI Chat 对话管理表
-- Oracle 数据库

-- 对话会话表
CREATE TABLE ai_chat_session (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR2(64) NOT NULL UNIQUE,
    user_id VARCHAR2(64) NOT NULL,
    title VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    linked_tree_ids CLOB,
    linked_doc_ids CLOB,
    status VARCHAR2(20) DEFAULT 'ACTIVE'
);

COMMENT ON TABLE ai_chat_session IS 'AI对话会话表';
COMMENT ON COLUMN ai_chat_session.session_id IS '会话ID';
COMMENT ON COLUMN ai_chat_session.user_id IS '用户ID';
COMMENT ON COLUMN ai_chat_session.title IS '会话标题';
COMMENT ON COLUMN ai_chat_session.linked_tree_ids IS '关联的故障树ID列表(JSON数组)';
COMMENT ON COLUMN ai_chat_session.linked_doc_ids IS '关联的文档ID列表(JSON数组)';
COMMENT ON COLUMN ai_chat_session.status IS '会话状态:ACTIVE,ARCHIVED';

CREATE INDEX idx_chat_session_user ON ai_chat_session(user_id);
CREATE INDEX idx_chat_session_updated ON ai_chat_session(updated_at DESC);

-- 对话消息表
CREATE TABLE ai_chat_message (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR2(64) NOT NULL UNIQUE,
    session_id VARCHAR2(64) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    content CLOB,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    metadata CLOB,
    FOREIGN KEY (session_id) REFERENCES ai_chat_session(session_id) ON DELETE CASCADE
);

COMMENT ON TABLE ai_chat_message IS 'AI对话消息表';
COMMENT ON COLUMN ai_chat_message.session_id IS '所属会话ID';
COMMENT ON COLUMN ai_chat_message.role IS '角色:user,assistant,system';
COMMENT ON COLUMN ai_chat_message.content IS '消息内容';
COMMENT ON COLUMN ai_chat_message.metadata IS '扩展元数据(JSON)';

CREATE INDEX idx_chat_message_session ON ai_chat_message(session_id);
CREATE INDEX idx_chat_message_timestamp ON ai_chat_message(timestamp);
